# Generated by Django 5.0.1 on 2025-10-22 02:45

import django.core.validators
import django.db.models.deletion
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('video_file', models.FileField(upload_to='videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'avi']), videos.models.validate_video_size], verbose_name='영상 파일')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), videos.models.validate_image_size], verbose_name='썸네일')),
                ('duration', models.PositiveIntegerField(default=0, help_text='영상 길이 (초 단위)', verbose_name='영상 길이')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='댓글 수')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='평균 평점')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='categories.category', verbose_name='카테고리')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='강사')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='categories.tag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '영상',
                'verbose_name_plural': '영상 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완강 여부')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완강일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_videos', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='videos.video', verbose_name='영상')),
            ],
            options={
                'verbose_name': '완강 체크',
                'verbose_name_plural': '완강 체크 목록',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['instructor', '-created_at'], name='videos_vide_instruc_08b550_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_public', '-created_at'], name='videos_vide_is_publ_3f5720_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-view_count'], name='videos_vide_view_co_02bc14_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-rating_avg'], name='videos_vide_rating__062fd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videocompletion',
            unique_together={('user', 'video')},
        ),
    ]
