# Generated by Django 5.0.1 on 2025-10-22 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='채택 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변 목록',
                'ordering': ['-is_accepted', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_answered', models.BooleanField(default=False, verbose_name='답변 완료 여부')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for', to='community.answer', verbose_name='채택된 답변')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('video', models.ForeignKey(blank=True, help_text='특정 영상 관련 질문일 경우', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='videos.video', verbose_name='관련 영상')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='community.question', verbose_name='질문'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='community_q_created_52448f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['video', '-created_at'], name='community_q_video_i_d3c704_idx'),
        ),
    ]
